### ISSUE TITLE
How do i connect to a pod with the pod name ?

### ISSUE THREAD

**Issue by libracoder** [cloudtty/cloudtty#285]
How do i connect to a pod with the pod name, muy use case requires connecting to apod

**Comment by calvin0327** [comment]
Do you mean `exec` into the pod.  If so, the following example can be used：

```yaml
apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: local-cluster-sample
spec:
  commandAction: "kubectl exec -it -n <namespace> <pod> -- sh"
```
