### ISSUE TITLE
Bug: the service account `cloudshell-xxxx-controller-manager` is not deleted when CR deleted

### ISSUE THREAD

**Issue by panpan0000** [cloudtty/cloudtty#32]
should add ownerReferences
```
  ownerReferences:
  - apiVersion: cloudshell.cloudtty.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: CloudShell
    name: cxxxx
```
