### ISSUE TITLE
Allow pod to run indefinitely

### ISSUE THREAD

**Issue by edu-diaz** [cloudtty/cloudtty#363]
Hi there!

This is a feature proposal which I would like to merge, however I want to share it here first in case it make sense. I have an use case where I would like to have the cloudshell pod indefinitely, but at this moment it is limited to the [TTL](https://github.com/cloudtty/cloudtty/blob/main/pkg/apis/cloudshell/v1alpha1/types.go#L69).

The solution I propose is adding a new CloudShellSpec boolean field called "RunIndefinitely" or something like that which, instead creating a job, it creates a pod and keeps it running forever.

Let me know if this makes sense to you. If so, I will propose a PR.

Thanks!

**Comment by calvin0327** [comment]
@edu-diaz Thanks for your fellback. 

In the latest release `v0.6.2`, we've implemented a permanent pod for cloudshell, which can be used forever if you don't set the TTLSecondsAfterStarted field.

**Comment by edu-diaz** [comment]
That's great @calvin0327 I'll test it now! Closing the issue

**Comment by edu-diaz** [comment]
Hi @calvin0327 I noticed that if I don't specify it, it stops working after 1h. I guess that's because of [this?](https://github.com/cloudtty/cloudtty/blob/main/pkg/apis/cloudshell/v1alpha1/defaults.go#L32)
Can you show me an example of a cloudshell CR? This is the one I am using on v0.6.2:
```
apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: cloudshell
  namespace: "cloudtty"
spec:
 secretRef:
   name: "kube-config"
 exposureMode: "NodePort"
```
