### ISSUE TITLE
clodushell worker pod 不支持设置节点亲和以及资源配额（request、limit）

### ISSUE THREAD

**Issue by leolingg** [cloudtty/cloudtty#530]
# 问题描述
clodushell worker pod 不支持设置节点亲和以及资源配额（request、limit）。

# 预期
可以通过配置支持设置 clodushell worker pod  的节点亲和以及资源配额（request、limit）。

**Comment by panguicai008** [comment]
## feature run
You can test it by running the following command 
```shell
go run cmd/main.go --kubeconfig=xxxx --cloudshell-image=xxx --leader-elect-resource-namespace=xxx --cloudshell-node-selector kubernetes.io/hostname=worker-xxxx --cloudshell-node-selector kubernetes.io/os=linux --v=2 --cloudshell-resources='{"limits": {"cpu": "1","memory": "1Gi"},"requests": {"cpu": "10m","memory": "10Mi"}}'
```

Additionally, in the kubernetes cloudtty controller manager deployment yaml orchestration, it can be specified as follows，which has the same effect as installing helm chart and specifying the --dry-run parameter
```yaml
command:
- manager
- '--leader-elect-resource-namespace=xxx'
- >-
    --cloudshell-image=xxx
- '--v=2'
- '--cloudshell-node-selector'
- kubernetes.io/hostname=worker-10-29-231-107
- '--cloudshell-node-selector'
- kubernetes.io/os=linux
- >-
    --cloudshell-resources={"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"10m","memory":"10Mi"}}
```

## feature validate
When a new worker pod is created, it will run using the specified node selector and resources parameters, as shown below

```yaml
apiVersion: v1
kind: Pod
metadata:
  finalizers:
  - cloudshell.cloudtty.io/worker-pool
  labels:
    worker.cloudtty.io/binding-count: "3"
    worker.cloudtty.io/name: cloudshell-worker-jjqmmmpl2b
    worker.cloudtty.io/owner-name: ""
  name: cloudshell-worker-jjqmmmpl2b
  namespace: xxx
spec:
  containers:
  - command:
    - /bin/bash
    - -ec
    - |
      while :; do sleep 2073600; done
    image: xxx
    imagePullPolicy: IfNotPresent
    name: web-tty
    ports:
    - containerPort: 7681
      name: tty-ui
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 10Mi
  nodeName: worker-xxx
  nodeSelector:
    kubernetes.io/hostname: worker-xxx
    kubernetes.io/os: linux
  restartPolicy: Never
```
